<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace />
    <RuntimeIdentifiers>$(AvailableRuntimeIdentifiers)</RuntimeIdentifiers>
    <RuntimeIdentifier>$(DefaultRuntimeIdentifier)</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nerdbank.Cryptocurrencies\Nerdbank.Cryptocurrencies.csproj" />
    <ProjectReference Include="..\..\src\Nerdbank.Zcash\Nerdbank.Zcash.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Shared\*.cs" LinkBase="Shared" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Validation" />
    <PackageReference Include="TUnit.Engine" />
    <PackageReference Include="xunit.v3.assert.aot" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)','net9.0'))" />
    <PackageReference Include="xunit.v3.assert" Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)','net9.0'))" />
  </ItemGroup>

  <Import Project="$(RepoRootPath)src\Nerdbank.Zcash\NativeBindings.targets" />
</Project>
