name: Publish artifacts
description: Publish artifacts
inputs:
  suffix:
    description: 'Suffix to append to the artifact name'
    required: true
  skipDotNet:
    description: Skip publishing .NET related artifacts
    required: false
    default: false

runs:
  using: composite
  steps:
  - name: 游닌 Collect artifacts
    run: tools/artifacts/_stage_all.ps1
    shell: pwsh
    if: always()

# TODO: replace this hard-coded list with a loop that utilizes the NPM package at
# https://github.com/actions/toolkit/tree/main/packages/artifact (or similar) to push the artifacts.

  - name: 游닉 Upload project.assets.json files
    if: inputs.skipDotNet == false
    uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
    with:
      name: projectAssetsJson-${{ inputs.suffix }}
      path: ${{ runner.temp }}/_artifacts/projectAssetsJson
    continue-on-error: true
  - name: 游닉 Upload build_logs
    if: inputs.skipDotNet == false
    uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
    with:
      name: build_logs-${{ inputs.suffix }}
      path: ${{ runner.temp }}/_artifacts/build_logs
    continue-on-error: true
  - name: 游닉 Upload testResults
    if: inputs.skipDotNet == false
    uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
    with:
      name: testResults-${{ inputs.suffix }}
      path: ${{ runner.temp }}/_artifacts/testResults
    continue-on-error: true
  - name: 游닉 Upload coverageResults
    if: inputs.skipDotNet == false
    uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
    with:
      name: coverageResults-${{ inputs.suffix }}
      path: ${{ runner.temp }}/_artifacts/coverageResults
    continue-on-error: true
  - name: 游닉 Upload symbols
    if: inputs.skipDotNet == false
    uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
    with:
      name: symbols-${{ inputs.suffix }}
      path: ${{ runner.temp }}/_artifacts/symbols
    continue-on-error: true
  - name: 游닉 Upload rust
    if: always()
    uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
    with:
      name: rust-${{ inputs.suffix }}
      path: ${{ runner.temp }}/_artifacts/rust
  - name: 游닉 Upload ios_framework
    if: runner.os == 'macOS'
    uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
    with:
      name: ios_framework-${{ inputs.suffix }}
      path: ${{ runner.temp }}/_artifacts/ios_framework
