//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nerdbank.Zcash {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nerdbank.Zcash.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This address has an invalid checksum..
        /// </summary>
        internal static string InvalidAddressChecksum {
            get {
                return ResourceManager.GetString("InvalidAddressChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This address does not meet length requirements..
        /// </summary>
        internal static string InvalidAddressLength {
            get {
                return ResourceManager.GetString("InvalidAddressLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This address does not specify a recognized network..
        /// </summary>
        internal static string InvalidNetworkHeader {
            get {
                return ResourceManager.GetString("InvalidNetworkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The checksum for this address is missing or incorrect..
        /// </summary>
        internal static string InvalidPadding {
            get {
                return ResourceManager.GetString("InvalidPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sapling address must start with &apos;zs1&apos; or &apos;ztestsapling1&apos;..
        /// </summary>
        internal static string InvalidSaplingPreamble {
            get {
                return ResourceManager.GetString("InvalidSaplingPreamble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} address does to conform to expected requirements..
        /// </summary>
        internal static string InvalidXAddress {
            get {
                return ResourceManager.GetString("InvalidXAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All receivers must come from the same Zcash network..
        /// </summary>
        internal static string MixingNetworksInUANotAllowed {
            get {
                return ResourceManager.GetString("MixingNetworksInUANotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This address does not conform to any known format..
        /// </summary>
        internal static string UnrecognizedAddress {
            get {
                return ResourceManager.GetString("UnrecognizedAddress", resourceCulture);
            }
        }
    }
}
