<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Validation" />
    <PackageReference Include="TUnit.Engine" />
    <PackageReference Include="xunit.v3.assert.aot" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)','net9.0'))" />
    <PackageReference Include="xunit.v3.assert" Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)','net9.0'))" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Shared\*.cs" LinkBase="Shared" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nerdbank.Bitcoin\Nerdbank.Bitcoin.csproj" />
  </ItemGroup>

</Project>
